# Aleth: Ethereum C++ client, tools and libraries.
# Copyright 2016-2019 Aleth Authors.
# Licensed under the GNU General Public License, Version 3.

branches:
  only:
    - master
    - /release\/.+/
    - /v\d+\..+/
    - /release\/.+/
    - appveyor
    - hunter
os: Visual Studio 2017
configuration:
  - RelWithDebInfo
environment:
  TESTS: On
  GITHUB_USER_PASSWORD:
    secure: 7TuNppxpvI3M/IF1PfvzZ8LluCeCQAsdFoJY+KhNv/pe/rAw5HEsTjqdbyM1mEtd
cache:
  - build/deps -> cmake\Project**.cmake
install:
  - git submodule update --init --recursive

  # Python 3
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  - pip install requests gitpython

before_build: |
  if not exist build mkdir build
  cd build
  cmake -G "Visual Studio 15 2017 Win64" ..
build_script: |
  cmake --build . --config %CONFIGURATION% --target package
test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - scripts\tests.bat %TESTS% %CONFIGURATION% %APPVEYOR_BUILD_FOLDER% %ETHEREUM_DEPS_PATH%
artifacts:
  - path: build\aleth.zip
    name: aleth-windows.zip

# This is the deploy target for Windows which generates ZIPs per commit.
# We are in agreement that generating ZIPs per commit for the develop
# branch is probably just noise, so we only run this deployment target
# on 'release'.
#
# See https://www.appveyor.com/docs/deployment/github for information
# on GitHub Releases in Appveyor.
#
# You need to generate a GitHub personal access token for Appveyor
# See https://github.com/settings/tokens for more information on that.
# The token you generate there (in an encrypted form) is what is
# passed to this deployment target in the 'auth_token' parameter
# below.
deploy:
    prerelease: true
    provider: GitHub
    auth_token:
        secure: yukM9mHUbzuZSS5WSBLKSW0yGJerJEqAXkFhDhSHBBcKJE7GAryjQsdO9Kxh3yRv
    artifact: aleth-windows.zip
    on:
        branch: release
